### ISSUE TITLE
save_plot: dimensions not computed as documented?

### ISSUE THREAD

**Issue by testbird** [wilkelab/cowplot#10]
Hello there,
I followed https://cran.r-project.org/web/packages/cowplot/cowplot.pdf
to create some plotgrids files.

However, in the  pdf or svg files I get the dimensions do not seem to be computed based on definitions for the "base plot" size or ratios. (This is what the documentation suggested to me, and  looked very practical to me.)

It looks like the definitions are applied to the final entire plotgrid.

In the following example:
* I only get the two side-by-side plots with a proper 45 degree slope when the ratio is adjusted according to the grid dimensions (set to 2). 
* I only get two stacked plots with a proper 45 degree slope with a ratio of 0.5, however the graphics look crammed.

```
require(dplyr)
require(ggplot2)
require(cowplot)

tmp_plot1 <- data.frame(a=1:100, b=1:100) %>%
  ggplot(aes(x=a, y=b)) + geom_line()

tmp_plot2 <- tmp_plot1

tmp_plotgrid <- plot_grid(tmp_plot1, tmp_plot2, labels = c('A', 'B'))

save_plot("2-horizontal-plots_height-NA_aspect-1.pdf", tmp_plotgrid, base_aspect_ratio = 1)
save_plot("2-horizontal-plots_height-NA_aspect-2.pdf", tmp_plotgrid, base_aspect_ratio = 2)
save_plot("2-horizontal-plots_height-NA_aspect-3.pdf", tmp_plotgrid, base_aspect_ratio = 3)

tmp_plotgrid <- plot_grid(tmp_plot1, tmp_plot2, labels = c('A', 'B'), ncol = 1)

save_plot("2-vertical-plots_height-NA_aspect-0.5.pdf", tmp_plotgrid, base_aspect_ratio = 0.5)
save_plot("2-vertical-plots_height-NA_aspect-1.pdf", tmp_plotgrid, base_aspect_ratio = 1)
save_plot("2-vertical-plots_height-NA_aspect-2.pdf", tmp_plotgrid, base_aspect_ratio = 2)
save_plot("2-vertical-plots_height-NA_aspect-3.pdf", tmp_plotgrid, base_aspect_ratio = 3)
```

**Comment by clauswilke** [comment]
The problem is that `save_plot()` has no way of knowing what the dimensions of your plot grid are. So you have to tell it again, via the `ncol` and `nrow` options (which are = 1 by default):
```
save_plot("2-horizontal-plots_height-NA_aspect-1.pdf", tmp_plotgrid, base_aspect_ratio = 1, ncol = 2)
save_plot("2-vertical-plots_height-NA_aspect-1.pdf", tmp_plotgrid, base_aspect_ratio = 1, nrow = 2)
```

Note that to get perfectly square plots, you need to add `coord_fixed()` to your plots. The `base_aspect_ratio` is applied to the entire plot, not just the plot panel that holds the data. I would probably do the following in your case:
```
tmp_plot1 <- data.frame(a=1:100, b=1:100) %>%
  ggplot(aes(x=a, y=b)) + geom_line() + coord_fixed()
tmp_plot2 <- tmp_plot1
tmp_plotgrid <- plot_grid(tmp_plot1, tmp_plot2, labels = c('A', 'B'), ncol = 1)
save_plot("2-vertical-plots_height-NA_aspect-1.pdf", tmp_plotgrid, nrow = 2)
```
The default for `base_aspect_ratio` is  1.1 to make a little space for the y axis label (and possibly legend). In most cases, that works out well even if the actual plot area is supposed to be perfectly square.

**Comment by testbird** [comment]
Ah, ok, thank you very much for explaining. I wrongly thought the grid dimension was part of the plot_grid output of tmp_plotgrid.
