### ISSUE TITLE
R version requirement

### ISSUE THREAD

**Issue by oganm** [wilkelab/cowplot#21]
I was wondering if there is a functional reason for this version to require R 3.2. I manually installed it on my R 3.1.2 and all functions I tried seems to be compatible. No errors on installation and past scripts work without issues. Is there a test suite that I could run if information isn't available on this?

**Comment by oganm** [comment]
other people who tried this @funkhou9 @dojeda @jcizel @nignatiadis

**Comment by oganm** [comment]
I see now that it was mentioned before. Though it would still be nice if we could test it and avoid a possibly unnecessary version bump 
#16 #9

**Comment by clauswilke** [comment]
It probably works on any R version on which ggplot2 works. The recommendation for package writers is to set the R requirement to the version they are using, to be certain. That's what I did. I can't test older versions because I don't run them anymore, and going forward it would be difficult to continue establishing that the older R versions are still fine. Not sure what's the best way to deal with that.
