### ISSUE TITLE
Vertical alignment not working for switched axes

### ISSUE THREAD

**Issue by kendonB** [wilkelab/cowplot#30]
This package is fantastic! I like the switch axis functionality but would like to be able to combine it with vertical grid alignment and it doesn't seem to work:

    plot.mpg1 <- ggplot(mpg, aes(x = cty, y = hwy, colour = factor(cyl))) + 
      geom_point(size=2.5)
    plot.mpg2 <- ggplot(mpg, aes(x = cty, y = hwy, colour = factor(cyl))) + 
      geom_point(size=2.5)
    
    plot.mpg2 <- switch_axis_position(plot.mpg2, "y")
    plot_grid(plot.mpg1, plot.mpg2, nrow = 2, align = "v")

**Comment by kendonB** [comment]
Along the same lines, the alignment fails when trying to adjust the position of the axis titles using margins.

**Comment by clauswilke** [comment]
I'm sorry, there is no simple way to automate aligning heterogeneous graphs, since ggplot2 adds and removes columns depending on which elements are present in the graph. However, there is a simple workaround, which is explained at the bottom of [this vignette:](https://cran.r-project.org/web/packages/cowplot/vignettes/axis_position.html)
```
require(cowplot)
require(gtable) # needed for gtable_add_cols
plot.mpg1 <- ggplot(mpg, aes(x = cty, y = hwy, colour = factor(cyl))) + 
  geom_point(size=2.5)
plot.mpg2 <- ggplot(mpg, aes(x = cty, y = hwy, colour = factor(cyl))) + 
  geom_point(size=2.5)

plot.mpg2 <- switch_axis_position(plot.mpg2, "y")

# add the two additional columns that plot.mpg2 has
g1 <- ggplotGrob(plot.mpg1)
g1 <- gtable_add_cols(g1, plot.mpg2$widths[5:6], 4)

plot_grid(g1, plot.mpg2, nrow = 2, align = "v")
```
![rplot](https://cloud.githubusercontent.com/assets/4210929/13624687/facc378c-e575-11e5-9462-aab6392b4cdf.png)
