### ISSUE TITLE
plot arrangement powered by `gtable`

### ISSUE THREAD

**Issue by kohske** [wilkelab/cowplot#6]
Thanks really for this great packages.
I have one suggestion.

`ggplot2` uses `gtable` as its backend structure for grid-based plot generation.
`gtable` allows to arrange multiple plots keeping their panel sizes aligned.

Here are some examples, sorry for Japanese text, but the codes are easy to read :)
http://rpubs.com/kohske/84415

So, it is really excellent if `cowplot` support this kind of arrangement powered by `gtable`.
Then we can get grid plots with consistent size for all panes and axes.

Feel free please to ask anything, if you have any question regarding usage of `gtable`, as I'm one of the committer of the package.

Thanks again.

-k

**Comment by clauswilke** [comment]
Hello,

I'm not sure how this would work, since the whole point of cowplot is to provide a continuous canvas that is not broken into pieces. However, one could first align plots with gtable and then place the aligned plots onto the cowplot canvas and annotate.

In any case, if you want to propose specific additional functionality, I'm happy to consider patches.

**Comment by clauswilke** [comment]
The plot_grid() function now knows about gtable and can do some basic alignment tasks. For more sophisticated alignments, I think the correct procedure is to arrange the plots with gtable first and then just use cowplot to add labels wherever needed.
