### ISSUE TITLE
new version (v0.91) cannot be installed on windows, because of the "blank" character in (c:/Program Files/R/...)

### ISSUE THREAD

**Issue by roison** [wilkelab/cowplot#81]
And Thanks for your packages.

**Comment by clauswilke** [comment]
You'll have to provide some details of what exactly you do, what happens, and what error messages you get. You'll also have to show that the problem is specific to cowplot 0.9 and not a generic problem with your setup.

Also, I'd like to point out that as of right now, a windows binary for 0.9.1 hasn't even been published yet: https://cran.r-project.org/web/packages/cowplot/index.html It will probably come out today or tomorrow.

**Comment by roison** [comment]
Hi, sorry for the uncleared message I posted.
The problem is, when I used "install.packages()" to install new version of cowplot, after successful downloaded it, the console window reported that it cannot identify "C:/Program".  Same error message reported after I tried to install manually using downloaded tar files.
Then I google this. Some answers tell me that because the space character (" ") in Windows OS default install directory(C:/Program Files/R/...., i.e., " " in "Program Files"),  many R packages developed by non-Windows OS cannot identify this annoyed space character and reported errors.  
To solve this problem, I reinstalled R in C root directory, and reinstalled cowplot, it is OK now.
Thank you again for this amazing package and amazing new functions!
