### ISSUE TITLE
plot_grid not aligned when ggdraw is used

### ISSUE THREAD

**Issue by ilyasustun** [wilkelab/cowplot#85]
Plots 2 and 6 are not aligned well with the rest. These plots used ggdraw after creating the plot using ggplot. After ggdraw they lose their ability to align with the rest. plots 1, 3, and 5 are straight out of ggplot, and they align well.
![capture](https://user-images.githubusercontent.com/7421957/34226083-95866960-e596-11e7-9725-4123849f94ad.PNG)

**Comment by clauswilke** [comment]
Yes, that can't be avoided, due to how `ggdraw()` works. (You can think of it as taking a snapshot of the plot so that you can then draw on top of it.) You need to align first and then draw. You can align plots outside of the `plot_grid` function, see the last example in the [vignette here.](https://cran.r-project.org/web/packages/cowplot/vignettes/shared_legends.html)

**Comment by ilyasustun** [comment]
Perfect. Thank you so much!!!

Do you happen to know a way to add a common number label that shows the multiplication value in the axis? Such as the one in the top left of the plot. I have found a way to do this. Just wanna see if there's a more effective way. Also, currently the position changes when you drag the plot and change its size. I need to get the y axis location and position the label accordingly. 
![capture](https://user-images.githubusercontent.com/7421957/34233129-91da415e-e5b1-11e7-8ebf-66b854dd60ce.PNG)

**Comment by clauswilke** [comment]
No, sorry, I can't think of a simple and straightforward way to do this. If you know the final size of your figure then you can always fiddle with the coordinates to get this label positioned right, but you are correct that the moment you change the figure size (or output format, e.g. pdf vs png) the location of the label will change.
