### ISSUE TITLE
save_plot with dimensions not working

### ISSUE THREAD

**Issue by fungs** [wilkelab/cowplot#90]
In cowplot 0.9.2 and earlier, if I use the save_plot function and pass it a width and hight argument, it does not work due to ambiguity.

    save_plot("out.pdf", p, width=297, height=210, units="mm")

Error message:

```
Error in cowplot::ggsave(filename = filename, plot = plot, width = base_width *  : 
  formal argument "width" matched by multiple actual arguments
Calls: save_plot
Execution halted
```

Instead, calling ggsave works.

**Comment by clauswilke** [comment]
I finally had a chance to look at this. That it worked in the past was an accident, because you're misusing the `save_plot()` API. You should specify `base_width` and `base_height` instead of `width` and `height`, and then it works as expected:
```{r}
save_plot("out.pdf", p, base_width=297, base_height=210, units="mm")
```
Also, the benefit of `save_plot()` is the width and height calculations if you're making larger plot grids. If you're simply specifying width and height in absolute values then there's no benefit to using `save_plot()` over `ggsave()`.

Leaving this issue open for now because I want to ponder a bit longer whether this should be fixed. In any case, things currently work as expected.

**Comment by fungs** [comment]
Thanks, I will try this next time I use cowplot. I don't remember exactly why I used save_plot over ggsave, but there was a specific reason.

**Comment by clauswilke** [comment]
Usage of `width` or `height` now creates a meaningful error.

**Comment by fungs** [comment]
Great!
